"""empty message

Revision ID: 563663343487
Revises: eaefefd80de5
Create Date: 2022-03-10 22:00:22.104947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563663343487'
down_revision = 'eaefefd80de5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_category_name_key', 'categories', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('categories_category_name_key', 'categories', ['category_name'])
    # ### end Alembic commands ###
