"""empty message

Revision ID: f00f5e225cb9
Revises: 318f72460b8d
Create Date: 2022-03-10 21:04:53.351540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f00f5e225cb9'
down_revision = '318f72460b8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transactions_trans_payee'), 'transactions', ['trans_payee'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_trans_payee'), table_name='transactions')
    # ### end Alembic commands ###
