"""empty message

Revision ID: fb112870b342
Revises: b991d046d30f
Create Date: 2022-01-30 00:16:02.492481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb112870b342'
down_revision = 'b991d046d30f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('budgets_budget_name_key', 'budgets', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('budgets_budget_name_key', 'budgets', ['budget_name'])
    # ### end Alembic commands ###
