"""empty message

Revision ID: 318f72460b8d
Revises: fb112870b342
Create Date: 2022-01-30 00:44:11.217712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318f72460b8d'
down_revision = 'fb112870b342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accounts_account_name_key', 'accounts', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('accounts_account_name_key', 'accounts', ['account_name'])
    # ### end Alembic commands ###
